# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default=b'', max_length=64)),
                ('last', models.CharField(default=b'', max_length=64)),
                ('state', localflavor.us.models.USStateField(default=b'', max_length=2)),
                ('district', models.CharField(default=b'', max_length=64)),
                ('party', models.CharField(blank=True, default=b'', max_length=1)),
                ('healthcare', models.NullBooleanField()),
                ('college_tuition', models.NullBooleanField()),
                ('minimum_wage', models.NullBooleanField()),
                ('workers_rights', models.NullBooleanField()),
                ('womens_rights', models.NullBooleanField()),
                ('voting_rights', models.NullBooleanField()),
                ('justice', models.NullBooleanField()),
                ('climate', models.NullBooleanField()),
            ],
        ),
    ]
