# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerforprogress', '0002_representative_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
